/* THIS IS A GENERATED/BUNDLED FILE. DO NOT EDIT. */
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => OpenTermPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var SECTION_ID = "openterm";
var DEFAULT_SETTINGS = {
  showDefaultTerminal: true,
  showPowerShell: true,
  showCmd: true,
  windowsDefaultExe: "cmd.exe",
  powershellExe: "pwsh",
  cmdExe: "cmd.exe",
  macTerminalApp: "Terminal",
  linuxTerminalExe: "x-terminal-emulator"
};
function hasBasePath(adapter) {
  return typeof adapter.getBasePath === "function";
}
function getDirectory(vaultBasePath, file) {
  var _a, _b;
  if (file instanceof import_obsidian.TFolder) {
    return path.join(vaultBasePath, file.path);
  }
  return path.join(vaultBasePath, (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "");
}
function openInDefaultTerminal(directory, settings) {
  if (import_obsidian.Platform.isWin) {
    const exe = settings.windowsDefaultExe || "cmd.exe";
    (0, import_child_process.execFile)("cmd.exe", ["/c", "start", "/D", directory, exe]);
  } else if (import_obsidian.Platform.isMacOS) {
    const app = settings.macTerminalApp || "Terminal";
    (0, import_child_process.execFile)("open", ["-a", app, directory]);
  } else {
    const exe = settings.linuxTerminalExe || "x-terminal-emulator";
    (0, import_child_process.execFile)(exe, [`--working-directory=${directory}`], (err) => {
      if (err) {
        (0, import_child_process.execFile)("xdg-open", [directory]);
      }
    });
  }
}
function openInPowerShell(directory, settings) {
  const exe = settings.powershellExe || "pwsh";
  const psArgs = [
    "-NoExit",
    "-Command",
    `Set-Location -LiteralPath '${directory.replace(/'/g, "''")}'`
  ];
  if (import_obsidian.Platform.isWin) {
    (0, import_child_process.execFile)("cmd.exe", ["/c", "start", exe, ...psArgs], (err) => {
      const isNotFound = err && err.code === "ENOENT";
      if (isNotFound && exe !== "powershell") {
        (0, import_child_process.execFile)("cmd.exe", ["/c", "start", "powershell", ...psArgs]);
      }
    });
  } else {
    (0, import_child_process.execFile)(exe, psArgs);
  }
}
function openInCmd(directory, settings) {
  const exe = settings.cmdExe || "cmd.exe";
  (0, import_child_process.execFile)("cmd.exe", ["/c", "start", "/D", directory, exe]);
}
var OpenTermPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new OpenTermSettingTab(this.app, this));
    const adapter = this.app.vault.adapter;
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        const basePath = hasBasePath(adapter) ? adapter.getBasePath() : "";
        const directory = getDirectory(basePath, file);
        if (this.settings.showDefaultTerminal) {
          menu.addItem((item) => {
            item.setTitle("Open in terminal").setIcon("terminal").setSection(SECTION_ID).onClick(() => openInDefaultTerminal(directory, this.settings));
          });
        }
        if (this.settings.showPowerShell) {
          menu.addItem((item) => {
            item.setTitle("Open in PowerShell").setIcon("terminal").setSection(SECTION_ID).onClick(() => openInPowerShell(directory, this.settings));
          });
        }
        if (import_obsidian.Platform.isWin && this.settings.showCmd) {
          menu.addItem((item) => {
            item.setTitle("Open in CMD").setIcon("terminal").setSection(SECTION_ID).onClick(() => openInCmd(directory, this.settings));
          });
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var OpenTermSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Context menu items").setHeading();
    new import_obsidian.Setting(containerEl).setName("Show default terminal").setDesc("Show the 'Open in terminal' option in the context menu.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showDefaultTerminal).onChange(async (value) => {
        this.plugin.settings.showDefaultTerminal = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show PowerShell").setDesc("Show the 'Open in PowerShell' option in the context menu.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showPowerShell).onChange(async (value) => {
        this.plugin.settings.showPowerShell = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Show CMD (Windows only)").setDesc("Show the 'Open in CMD' option in the context menu.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showCmd).onChange(async (value) => {
        this.plugin.settings.showCmd = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Executables").setHeading();
    new import_obsidian.Setting(containerEl).setName("PowerShell executable").setDesc("Executable for PowerShell. Uses 'pwsh' (PowerShell 7+) by default, falling back to 'powershell' on Windows if not found.").addText(
      (text) => text.setPlaceholder("pwsh").setValue(this.plugin.settings.powershellExe).onChange(async (value) => {
        this.plugin.settings.powershellExe = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("CMD executable (Windows)").setDesc("Executable for Command Prompt on Windows.").addText(
      (text) => text.setPlaceholder("cmd.exe").setValue(this.plugin.settings.cmdExe).onChange(async (value) => {
        this.plugin.settings.cmdExe = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default terminal executable (Windows)").setDesc("Executable used for the default terminal option on Windows.").addText(
      (text) => text.setPlaceholder("cmd.exe").setValue(this.plugin.settings.windowsDefaultExe).onChange(async (value) => {
        this.plugin.settings.windowsDefaultExe = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Terminal app (macOS)").setDesc("Application used for the default terminal option on macOS.").addText(
      (text) => text.setPlaceholder("Terminal").setValue(this.plugin.settings.macTerminalApp).onChange(async (value) => {
        this.plugin.settings.macTerminalApp = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Terminal executable (Linux)").setDesc("Executable used for the default terminal option on Linux.").addText(
      (text) => text.setPlaceholder("x-terminal-emulator").setValue(this.plugin.settings.linuxTerminalExe).onChange(async (value) => {
        this.plugin.settings.linuxTerminalExe = value.trim();
        await this.plugin.saveSettings();
      })
    );
  }
};
